local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'

sortable_fields: ['title', 'year']

collections:
  - name: posts
    label: Posts
    folder: 'src/content/post'
    label_singular: 'Post'
    path: '{{slug}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Heading title', name: 'headingTitle', widget: 'text' }
      - { label: 'Introduction', name: 'introduction', widget: 'text' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - {
        label: 'Roles',
        name: 'roles',
        widget: 'relation',
        collection: "role",
        search_fields: ["title"],
        value_field: "title",
        multiple: true,
      }
      - {
        label: 'Services',
        name: 'services',
        widget: 'relation',
        collection: "service",
        search_fields: ["title"],
        value_field: "title",
        multiple: true,
      }
      - {
        label: 'Outcomes',
        name: 'sellingPoints',
        widget: 'list',
        allow_add: true,
        allow_delete: true,
        collapsed: false,
        field: { label: 'Point', name: 'point', widget: 'string' },
      }
      - {
        label: 'Image',
        name: 'image',
        widget: 'image',
        choose_url: false,
        allow_multiple: false,
        media_folder: '',
        public_folder: ''
      }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - label: 'Link visit'
        name: 'visitLink'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: false }
          - { label: 'Link', name: 'link', widget: 'string', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'service'
    label: 'Service'
    folder: 'src/content/service'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'role'
    label: 'Role'
    folder: 'src/content/role'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'src/content/pages/home/index.md'
        path: '{{slug}}/index'
        fields:
          - name: 'meta'
            label: 'SEO'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Meta description', name: 'desc', widget: 'string' }
              - { label: 'Open graph', name: 'open_graph', widget: 'image' }
              - { label: 'Open graph alt', name: 'open_graph_alt', widget: 'string' }
          - name: 'hero'
            label: 'Hero Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - name: 'title_slider'
                label: 'Title Slider'
                widget: 'list'
                fields:
                  - { name: 'text', label: 'Text', widget: 'string' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - {
                label: 'Services',
                name: 'services',
                widget: 'relation',
                collection: "service",
                search_fields: ["title"],
                value_field: "title",
                multiple: true,
              }
              - label: 'Awards'
                name: 'awards'
                widget: 'list'
                fields:
                  - { name: 'logo', label: 'Logo', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
          - name: 'intro'
            label: 'Introduction Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
              - label: 'Companies'
                name: 'companies'
                widget: 'list'
                fields:
                  - { name: 'name', label: 'Name', widget: 'string' }
                  - { name: 'logo', label: 'Logo', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
              - label: 'Awards'
                name: 'awards'
                widget: 'list'
                fields:
                  - { name: 'name', label: 'Name', widget: 'string' }
                  - { name: 'year', label: 'Year', widget: 'string' }
                  - { name: 'category', label: 'Category', widget: 'string' }
                  - { name: 'logo', label: 'Logo', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
              - label: 'Services Marquee'
                name: 'service'
                widget: 'object'
                fields:
                  - name: 'orange'
                    label: 'Orange'
                    widget: 'list'
                    fields:
                      - { name: 'text', label: 'Text', widget: 'string' }
                  - name: 'black'
                    label: 'Black'
                    widget: 'list'
                    fields:
                      - { name: 'text', label: 'Text', widget: 'string' }
          - label: 'Testimonial Section'
            name: 'testimonial'
            widget: 'object'
            fields:
              - name: 'testifiers'
                label_singular: 'Testifier'
                label: 'Testifiers'
                widget: 'list'
                fields:
                  - { name: 'name', label: 'Name', widget: 'string' }
                  - { name: 'position', label: 'Position', widget: 'string' }
                  - { name: 'feedback', label: 'Feedback', widget: 'text' }
                  - { name: 'avatar', label: 'Avatar', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
          - label: 'Last call'
            name: 'last_call'
            widget: 'object'
            fields:
              - { name: title, label: 'Title', widget: 'text' }
              - { name: cta_title, label: 'CTA Title', widget: 'string' }
              - { name: cta_sub, label: 'CTA Subtitle', widget: 'string' }
      - name: 'about'
        label: 'About'
        file: 'src/content/pages/about/index.md'
        path: '{{slug}}/index'
        fields:
          - name: 'meta'
            label: 'SEO'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Meta description', name: 'desc', widget: 'string' }
              - { label: 'Open graph', name: 'open_graph', widget: 'image' }
              - { label: 'Open graph alt', name: 'open_graph_alt', widget: 'string' }
          - name: 'hero'
            label: 'Hero Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'text' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - { label: 'Subtitle2', name: 'subtitle2', widget: 'text' }
              - {
                label: 'Image',
                name: 'image',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
                media_folder: './uploads',
                public_folder: './uploads'
              }
              - {
                label: 'Image2',
                name: 'image2',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
                media_folder: './uploads',
                public_folder: './uploads'
              }
          - name: 'vision'
            label: 'Vision Section'
            widget: 'object'
            fields:
              - { label: 'Content', name: 'content', widget: 'text' }
          - name: 'work'
            label: 'Work Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'text' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - { label: 'Subtitle2', name: 'subtitle2', widget: 'text' }
          - name: 'services'
            label: 'Services Section'
            widget: 'object'
            fields:
              - name: 'title_slider'
                label: 'Title Slider'
                widget: 'list'
                fields:
                  - { name: 'text', label: 'Text', widget: 'string' }
              - {
                label: 'Services',
                name: 'services',
                widget: 'relation',
                collection: "service",
                search_fields: ["title"],
                display_fields: ["title"],
                value_field: "{{slug}}",
                multiple: true,
              }
          - name: 'daily'
            label: 'Daily Section'
            widget: 'object'
            fields:
              - { label: 'Content', name: 'content', widget: 'text' }
              - {
                label: 'Image',
                name: 'image',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
                media_folder: './uploads',
                public_folder: './uploads'
              }
          - name: 'history'
            label: 'History Section'
            widget: 'object'
            fields:
              - name: 'title_slider'
                label: 'Title Slider'
                widget: 'list'
                fields:
                  - { name: 'text', label: 'Text', widget: 'string' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - { label: 'Subtitle2', name: 'subtitle2', widget: 'text' }
              - name: 'working_history'
                label: 'Working History'
                widget: 'list'
                label_singular: 'Position'
                add_to_top: true
                summary: '{{fields.company.name}} - {{fields.position.title}}'
                fields:
                  - name: 'position'
                    label: 'Position'
                    widget: 'object'
                    fields:
                      - { name: 'title', label: 'Title', widget: 'string' }
                      - { name: 'type', label: 'Type', widget: 'select', options: ["Internship", "Full-time", "Contract"] }
                  - name: 'company'
                    label: 'Company'
                    widget: 'object'
                    fields:
                      - { name: 'name', label: 'Name', widget: 'string' }
                      - { name: 'location', label: 'Location', widget: 'string' }
                      - { name: 'logo', label: 'Logo', widget: 'image', media_folder: './uploads', public_folder: './uploads'}
                  - name: 'period'
                    label: 'Period'
                    widget: 'object'
                    fields:
                      - { name: 'from', label: 'From', widget: datetime, format: 'MMM, YYYY' }
                      - { name: 'to', label: 'To', widget: datetime, format: 'MMM, YYYY' }
                  - name: 'description'
                    label: 'Job Description'
                    widget: 'markdown'
          - name: 'bringing'
            label: 'Bringing Section'
            widget: 'object'
            fields:
                - { name: 'title', label: 'Title', widget: 'string' }
                - name: bringings
                  label: 'Bringing listing'
                  widget: list
                  max: 2
                  label_singular: 'Bringing'
                  fields:
                    - { name: 'title', label: 'Title', widget: 'string' }
                    - { name: 'title_slider', label: 'Title Slider', widget: 'list', summary: '{{fields.text}}', field: { name: 'text', label: 'Text', widget: 'string' } }
                - { name: cta_title, label: 'CTA Title', widget: 'string' }
                - { name: cta_sub, label: 'CTA Subtitle', widget: 'string' }
      - name: 'projects'
        label: 'Projects'
        file: 'src/content/pages/projects/index.md'
        path: '{{slug}}/index'
        fields:
          - name: 'meta'
            label: 'SEO'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Meta description', name: 'desc', widget: 'string' }
              - { label: 'Open graph', name: 'open_graph', widget: 'image' }
              - { label: 'Open graph alt', name: 'open_graph_alt', widget: 'string' }
  - name: 'navigation'
    label: 'Navigation'
    files:
      - name: 'social'
        label: 'Social'
        file: 'src/content/navigation/social.md'
        fields:
          - name: 'networks'
            label: 'Networks'
            label_singular: 'Network'
            widget: list
            fields:
              - { name: 'text', label: 'Text', widget: 'string' }
              - { name: 'shorthand', label: 'Shorthand', widget: 'string' }
              - { name: 'link', label: 'Link', widget: 'string' }
          - { name: 'phone', label: 'Phone number', widget: 'string' }









