local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'

sortable_fields: ['title', 'year']

collections:
  - name: posts
    label: Posts
    folder: 'src/content/post'
    label_singular: 'Post'
    path: '{{slug}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Heading title', name: 'headingTitle', widget: 'text' }
      - { label: 'Introduction', name: 'introduction', widget: 'text' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - {
        label: 'Roles',
        name: 'roles',
        widget: 'relation',
        collection: "role",
        search_fields: ["title"],
        value_field: "title",
        multiple: true,
      }
      - {
        label: 'Services',
        name: 'services',
        widget: 'relation',
        collection: "service",
        search_fields: ["title"],
        value_field: "title",
        multiple: true,
      }
      - {
        label: 'Selling points',
        name: 'sellingPoints',
        widget: 'list',
        allow_add: true,
        allow_delete: true,
        collapsed: false,
        field: { label: 'Point', name: 'point', widget: 'string' },
      }
      - {
        label: 'Image',
        name: 'image',
        widget: 'image',
        choose_url: false,
        allow_multiple: false,
        media_folder: '',
        public_folder: ''
      }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'service'
    label: 'Service'
    folder: 'src/content/service'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
  - name: 'role'
    label: 'Role'
    folder: 'src/content/role'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
