local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: 'public/images'

sortable_fields: ['title', 'year']

collections:
  - name: posts
    label: Posts
    folder: 'src/content/post'
    label_singular: 'Post'
    path: '{{slug}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Heading title', name: 'headingTitle', widget: 'text' }
      - { label: 'Introduction', name: 'introduction', widget: 'text' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - {
        label: 'Roles',
        name: 'roles',
        widget: 'relation',
        collection: "role",
        search_fields: ["title"],
        value_field: "title",
        multiple: true,
      }
      - {
        label: 'Services',
        name: 'services',
        widget: 'relation',
        collection: "service",
        search_fields: ["title"],
        value_field: "title",
        multiple: true,
      }
      - {
        label: 'Selling points',
        name: 'sellingPoints',
        widget: 'list',
        allow_add: true,
        allow_delete: true,
        collapsed: false,
        field: { label: 'Point', name: 'point', widget: 'string' },
      }
      - {
        label: 'Image',
        name: 'image',
        widget: 'image',
        choose_url: false,
        allow_multiple: false,
        media_folder: '',
        public_folder: ''
      }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'service'
    label: 'Service'
    folder: 'src/content/service'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'role'
    label: 'Role'
    folder: 'src/content/role'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'src/content/pages/home/index.md'
        path: '{{slug}}/index'
        fields:
          - name: 'hero'
            label: 'Hero Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - { label: 'Scopes', name: 'scopes', widget: 'relation', collection: 'role' , search_fields: ["title"], value_field: "title", multiple: true }
              - label: 'Awards'
                name: 'awards'
                widget: 'list'
                fields:
                  - { name: 'logo', label: 'Logo', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
          - name: 'intro'
            label: 'Introduction Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'text' }
              - label: 'Companies'
                name: 'companies'
                widget: 'list'
                fields:
                  - { name: 'name', label: 'Name', widget: 'string' }
                  - { name: 'logo', label: 'Logo', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
              - label: 'Awards'
                name: 'awards'
                widget: 'list'
                fields:
                  - { name: 'name', label: 'Name', widget: 'string' }
                  - { name: 'year', label: 'Year', widget: 'string' }
                  - { name: 'category', label: 'Category', widget: 'string' }
                  - { name: 'logo', label: 'Logo', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
              - label: 'Services Marquee'
                name: 'service'
                widget: 'object'
                fields:
                  - name: 'orange'
                    label: 'Orange'
                    widget: 'list'
                    fields:
                      - { name: 'text', label: 'Text', widget: 'string' }
                  - name: 'black'
                    label: 'Black'
                    widget: 'list'
                    fields:
                      - { name: 'text', label: 'Text', widget: 'string' }
          - label: 'Testimonial Section'
            name: 'testimonial'
            widget: 'object'
            fields:
              - name: 'testifiers'
                single_label: 'Testifier'
                label: 'Testifiers'
                widget: 'list'
                fields:
                  - { name: 'name', label: 'Name', widget: 'string' }
                  - { name: 'position', label: 'Position', widget: 'string' }
                  - { name: 'feedback', label: 'Feedback', widget: 'text' }
                  - { name: 'avatar', label: 'Avatar', widget: 'image', media_folder: './uploads', public_folder: './uploads' }
      - name: 'about'
        label: 'About'
        file: 'src/content/pages/about/index.md'
        path: '{{slug}}/index'
        fields:
          - name: 'hero'
            label: 'Hero Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'text' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - { label: 'Subtitle2', name: 'subtitle2', widget: 'text' }
              - {
                label: 'Image',
                name: 'image',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
                media_folder: '',
                public_folder: ''
              }
              - {
                label: 'Image2',
                name: 'image2',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
                media_folder: '',
                public_folder: ''
              }
          - name: 'vision'
            label: 'Vision Section'
            widget: 'object'
            fields:
              - { label: 'Content', name: 'content', widget: 'text' }
          - name: 'work'
            label: 'Work Section'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'text' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - { label: 'Subtitle2', name: 'subtitle2', widget: 'text' }
          - name: 'services'
            label: 'Services Section'
            widget: 'object'
            fields:
              - name: 'title_slider'
                label: 'Title Slider'
                widget: 'list'
                fields:
                  - { name: 'text', label: 'Text', widget: 'string' }
              - {
                label: 'Services',
                name: 'services',
                widget: 'relation',
                collection: "service",
                search_fields: ["title"],
                value_field: "title",
                multiple: true,
              }
          - name: 'daily'
            label: 'Daily Section'
            widget: 'object'
            fields:
              - { label: 'Content', name: 'content', widget: 'text' }
              - {
                label: 'Image',
                name: 'image',
                widget: 'image',
                choose_url: false,
                allow_multiple: false,
                media_folder: '',
                public_folder: ''
              }
          - name: 'history'
            label: 'History Section'
            widget: 'object'
            fields:
              - { label: 'Years of experience', name: 'years_of_experience', widget: 'number' }
              - name: 'title_slider'
                label: 'Title Slider'
                widget: 'list'
                fields:
                  - { name: 'text', label: 'Text', widget: 'string' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'text' }
              - { label: 'Subtitle2', name: 'subtitle2', widget: 'text' }
              - name: 'working_history'
                label: 'Working History'
                widget: 'list'
                fields:
                  - { name: 'title', label: 'Title', widget: 'string' }
                  - { name: 'type', label: 'Type', widget: 'select', options: ["Fulltime", "Contract"] }
                  - { name: 'Client', label: 'Text', widget: 'string' }





